### ISSUE TITLE
What mean string $service as parameter of many of function of this Package?

### ISSUE THREAD

**Issue by fgendorf** [avitacco/php-gravityzone-api#4]
Hi, I'm a little bit confuse about how to use this package, In any place of documentation of this package and in API from bitdefender exists an explanation about what is $service param, normally in the first position of function...
Can you explain?

Thanks for advance

**Comment by avitacco** [comment]
@fgendorf I apologize that it has taken me so long to get back to you on this question. I didn't get an email notification that anyone had asked anything.

But, Bitdefender differentiates between different types of machines they call services. This is something I find odd about the product, but the service in this case would be "virtualmachines" or "computers". You can see usage examples in the unit tests.
